### ISSUE TITLE
setup.py is busted

### ISSUE THREAD

**Issue by numberoverzero** [numberoverzero/kmeans#1]
reproducible with pip install, at least 2.7 & 3.4
looks like setup.py is broken

Downloading/unpacking kmeans
  Downloading kmeans-0.3.2.tar.gz
  Running setup.py egg_info for package kmeans
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip_build_root/kmeans/setup.py", line 2, in <module>
        import kmeans
    ImportError: No module named kmeans
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip_build_root/kmeans/setup.py", line 2, in <module>

```
import kmeans
```

ImportError: No module named kmeans

**Comment by numberoverzero** [comment]
Fixed in 00d993c1864eff16b9c51ddebd2ddf3a836f8382

Removed the py_modules line from setup so that it stops complaining about failing to find kmeans.py in 28e9ee8353d24d33615fcbd2772b128df149a6bb
