### ISSUE TITLE
ValueError when importing

### ISSUE THREAD

**Issue by chinatsu** [numberoverzero/kmeans#2]
Upon importing kmeans, the following error gets raised:
ValueError: number of bits invalid for bit field

Here's the traceback, and Python info:

```
Python 3.4.3 (default, Feb 26 2015, 16:19:21) 
[GCC 4.9.2 20150204 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kmeans
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/kmeans/__init__.py", line 40, in <module>
    class Center(Structure):
ValueError: number of bits invalid for bit field
```

**Comment by chinatsu** [comment]
It seems like changing c_ulong to c_ulonglong fixes this for users on 32bit, which was the cause of my issue.

**Comment by numberoverzero** [comment]
Thanks for the bug report!
